public class Pencere extends javax.swing.JFrame {

    /** Creates new form Pencere */
    public Pencere() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiket = new javax.swing.JLabel();
        yaricapKutusu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        metinAlan = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("01 DAİRE HESAPLARI (CIRCLE CALCULATION)");

        etiket.setText("Yarıçap giriniz (Enter radius) : ");

        yaricapKutusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaricapKutusuActionPerformed(evt);
            }
        });

        metinAlan.setEditable(false);
        metinAlan.setColumns(20);
        metinAlan.setRows(5);
        jScrollPane1.setViewportView(metinAlan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(etiket)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(yaricapKutusu))
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiket, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yaricapKutusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yaricapKutusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaricapKutusuActionPerformed
        double r = Double.parseDouble(yaricapKutusu.getText());
        metinAlan.setText(("Cevre (Circumference) = "+Double.toString(2*Math.PI*r))
        +("\n"+"Alan (Area) = "+Double.toString(Math.PI*r*r)));
    }//GEN-LAST:event_yaricapKutusuActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pencere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiket;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea metinAlan;
    private javax.swing.JTextField yaricapKutusu;
    // End of variables declaration//GEN-END:variables

}
