package CircleCalc_Visual_03Buttons_formatted_enter;
import java.text.NumberFormat;
public class Pencere extends javax.swing.JFrame {
    
    NumberFormat deger = NumberFormat.getNumberInstance();

    /** Creates new form Pencere */
    public Pencere() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiket = new javax.swing.JLabel();
        dugmeCikis = new javax.swing.JButton();
        yaricapKutusu = new javax.swing.JTextField();
        cevreKutusu = new javax.swing.JTextField();
        alanKutusu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dugmeHesap = new javax.swing.JButton();
        dugmeTemizle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("03 DAİRE HESAPLARI (CIRCLE CALCULATION)");

        etiket.setText("Yarıçap giriniz (Enter radius) : ");

        dugmeCikis.setText("ÇIKIŞ (Exit)");
        dugmeCikis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dugmeCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dugmeCikisActionPerformed(evt);
            }
        });

        yaricapKutusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yaricapKutusuActionPerformed(evt);
            }
        });

        cevreKutusu.setEditable(false);
        cevreKutusu.setFocusable(false);

        alanKutusu.setEditable(false);
        alanKutusu.setFocusable(false);

        jLabel1.setText("Çevre (Circumference) : ");

        jLabel2.setText("Alan (Area) : ");

        dugmeHesap.setText("Hesapla (Calculate)");
        dugmeHesap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dugmeHesapActionPerformed(evt);
            }
        });

        dugmeTemizle.setText("Temizle (Clear)");
        dugmeTemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dugmeTemizleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiket)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alanKutusu)
                            .addComponent(cevreKutusu)
                            .addComponent(yaricapKutusu)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dugmeTemizle)
                        .addGap(29, 29, 29)
                        .addComponent(dugmeHesap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(dugmeCikis)))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiket, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yaricapKutusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cevreKutusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alanKutusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dugmeCikis)
                    .addComponent(dugmeHesap)
                    .addComponent(dugmeTemizle))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dugmeCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dugmeCikisActionPerformed
        System.exit(0);
    }//GEN-LAST:event_dugmeCikisActionPerformed

    private void dugmeHesapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dugmeHesapActionPerformed
        double r = Double.parseDouble(yaricapKutusu.getText());
        cevreKutusu.setText(deger.format(2*Math.PI*r));
        alanKutusu.setText(deger.format(Math.PI*r*r));
        
    }//GEN-LAST:event_dugmeHesapActionPerformed

    private void yaricapKutusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yaricapKutusuActionPerformed
        dugmeHesapActionPerformed(evt);
        //double r = Double.parseDouble(yaricapKutusu.getText());
        //cevreKutusu.setText(Double.toString(2*Math.PI*r));
        //alanKutusu.setText(Double.toString(Math.PI*r*r));
    }//GEN-LAST:event_yaricapKutusuActionPerformed

    private void dugmeTemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dugmeTemizleActionPerformed
        yaricapKutusu.setText("");
        cevreKutusu.setText("");
        alanKutusu.setText("");
    }//GEN-LAST:event_dugmeTemizleActionPerformed

  
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pencere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alanKutusu;
    private javax.swing.JTextField cevreKutusu;
    private javax.swing.JButton dugmeCikis;
    private javax.swing.JButton dugmeHesap;
    private javax.swing.JButton dugmeTemizle;
    private javax.swing.JLabel etiket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField yaricapKutusu;
    // End of variables declaration//GEN-END:variables

}
